[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.28"
evm_version = "cancun"
remappings = [
    "@selfxyz/contracts/=node_modules/@selfxyz/contracts/",
    "@hyperlane-xyz/core/=node_modules/@hyperlane-xyz/core/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
celo-sepolia = "${CELO_RPC_URL}"

[etherscan]
celo-sepolia = { key = "${CELOSCAN_API_KEY}", url = "https://api-alfajores.celoscan.io/api" }
