[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
solc_version = "0.8.24"
remappings = [
    "@hyperlane-xyz/core/=node_modules/@hyperlane-xyz/core/",
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC}"

[etherscan]
base-sepolia = { key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
